apiVersion: v1
kind: PersistentVolume
metadata:
  name: credentials-pv
  labels:
    app: kube-credentials
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/credentials-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: credentials-pvc
  labels:
    app: kube-credentials
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  labels:
    app: kube-credentials
data:
  NODE_ENV: "production"
  DB_PATH: "/app/shared/credentials.db"
  # Add any other configuration here